# Generated by Django 5.0.6 on 2024-06-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_categories_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=255, unique=True, verbose_name='ссылка'),
            preserve_default=False,
        ),
    ]
